name: Wages CI

on:
  push:
    branches:
      - "**/**"
    tags-ignore:
      - "**"

defaults:
  run:
    shell: bash

permissions:
  id-token: write # required to use OIDC authentication
  contents: read # required to checkout the code from the repo

jobs:
  run-checks:
    runs-on: ubuntu-latest
    container: node:10.18-jessie
    services:
      postgres:
        image: postgres:12
        ports: ["5432:5432"]
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          elixir-version: "1.14"
          otp-version: "25.0"
      - run: mix deps.get
      - run: mix deps.compile
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: npm install --prefix assets --legacy-peer-deps
      - run: mix check --except dialyzer --except credo
        env:
          DATABASE_HOST: postgres
