name: Wages CI

on:
  push:
    branches:
      - "**/**"
    tags-ignore:
      - "**"

defaults:
  run:
    shell: bash

permissions:
  id-token: write # required to use OIDC authentication
  contents: read # required to checkout the code from the repo

jobs:
  run-checks:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        ports: ["5432:5432"]
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: "25.3.2"
          elixir-version: "1.15.0"
          hexpm-mirrors: |
            https://builds.hex.pm
            https://cdn.jsdelivr.net/hex
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: mix deps.get
      - name: Compile
        run: mix deps.compile
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install node dependencies
        run: npm install --prefix assets --legacy-peer-deps
      - name: Run mix run-checks
        run: mix check --except dialyzer --except credo
